/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hkhwgbkijepsxtixdmrs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraHdnYmtpamVwc3h0aXhkbXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NTM0NDksImV4cCI6MjA4OTIyOTQ0OX0.XS9fCpptCe-XoS4r6JlB08iRGS35Mb3MsDbw-_QMEG8"